/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    shop: Shop;
    catalogue: Catalogue;
    pdf: Pdf;
    article: Article;
    articleCategory: ArticleCategory;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: number;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Shop {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
export interface Catalogue {
  id: number;
  shop: number | Shop;
  name: string;
  catalogueUrl?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  pdf?: number | Pdf | null;
  updatedAt: string;
  createdAt: string;
}
export interface Pdf {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Article {
  id: number;
  name: string;
  articleCategory: number | ArticleCategory;
  catalogue: number | Catalogue;
  image?: number | Media | null;
  updatedAt: string;
  createdAt: string;
}
export interface ArticleCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}